// <auto-generated />
namespace Jitter.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class fluent_api__double_many_to_many : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fluent_api__double_many_to_many));
        
        string IMigrationMetadata.Id
        {
            get { return "201703131335077_fluent_api__double_many_to_many"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
