// <auto-generated />
namespace ShishaKingdom.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class more_info_to_cats : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(more_info_to_cats));
        
        string IMigrationMetadata.Id
        {
            get { return "201704021428467_more_info_to_cats"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
